In [1]:
import numpy as np

This is a numpy exercise. They come from the [Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)
<br> There is 70 question, so I will paste a question, and do the exercise.

#### 1. Import numpy as np and see the version

In [2]:
np.version.version

'1.17.2'

#### 2. Create a 1D array of numbers from 0 to 9

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Create a 3×3 numpy array of all True’s

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 4. Extract all odd numbers from arr

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
odds = [i for i in arr if i%2 == 1]

In [8]:
print(odds)

[1, 3, 5, 7, 9]


#### 5. Replace all odd numbers in arr with -1

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 6. Replace all odd numbers in arr with -1 without changing arr

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
out = np.where(arr%2, -1, arr)

In [13]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 7. Convert a 1D array to a 2D array with 2 rows

In [14]:
np.arange(10).reshape((2,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 8. Stack arrays a and b vertically

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [16]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 9. Stack the arrays a and b horizontally.

In [20]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [21]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### 10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [22]:
a = np.array([1,2,3])

Desired Output:
<br> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### 11. Get the common items between a and b

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [25]:
np.intersect1d(a,b)

array([2, 4])

#### 12. From array a remove all items present in array b

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [27]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

#### 13. Get the positions where elements of a and b match

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [29]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

#### 14. Get all items between 5 and 10 from a.

In [30]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [31]:
np.where((a >= 5) & (a <= 10))

(array([1, 3, 4], dtype=int64),)

In [32]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

#### 15. Convert the function maxx that works on two scalars, to work on two arrays.

In [33]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [34]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(1, 5)

5

In [35]:
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

#### 16. How to swap two columns in a 2d numpy array?

In [36]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 17. How to swap two rows in a 2d numpy array?

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 18. Reverse the rows of a 2D array arr.

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.flip(arr, 0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [42]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 19. Reverse the columns of a 2D array arr.

In [43]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.flip(arr, 1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [45]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

#### 20. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [46]:
np.random.uniform(5,10, size=(5,3))

array([[7.38808274, 9.26435108, 6.67903409],
       [5.13507485, 9.46352203, 7.41050738],
       [6.90332541, 9.95479505, 7.00909302],
       [8.09116908, 5.15729968, 5.69199825],
       [7.16589087, 7.26818201, 7.96921449]])

#### 21. Print or show only 3 decimal places of the numpy array rand_arr.

In [47]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.97622713, 0.85153136, 0.08775586],
       [0.09192484, 0.14703213, 0.74663095],
       [0.63657126, 0.59107045, 0.47654998],
       [0.59797787, 0.6446614 , 0.92068093],
       [0.87356386, 0.46681194, 0.73221508]])

In [48]:
rand_arr.round(3)

array([[0.976, 0.852, 0.088],
       [0.092, 0.147, 0.747],
       [0.637, 0.591, 0.477],
       [0.598, 0.645, 0.921],
       [0.874, 0.467, 0.732]])

#### 22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [49]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [50]:
np.set_printoptions(suppress=False)
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [51]:
np.set_printoptions(suppress=True)
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

#### 23. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [52]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

#### 24. Print the full numpy array a without truncating.

In [54]:
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [55]:
np.set_printoptions(threshold=1000)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 25. Import the iris dataset keeping the text intact.

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [57]:
iris[:2]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

#### 26. Extract the text column species from the 1D iris imported in previous question.

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')

In [59]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [60]:
species = np.array([row[4] for row in iris_1d])

In [61]:
species[:3]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa'], dtype='<U15')

#### 27. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')

In [63]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [64]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

#### 28. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [65]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')

In [66]:
sepallength = np.array([row[0] for row in iris])
sepallength[:2]

array([5.1, 4.9])

In [67]:
np.mean(sepallength)

5.843333333333334

In [68]:
np.median(sepallength)

5.8

In [69]:
np.std(sepallength)

0.8253012917851409

#### 29. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0], encoding='utf-8')

In [71]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
S[:5]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])

In [72]:
S = (sepallength - Smin)/sepallength.ptp()
S[:5]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])

In [73]:
sepallength[0:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

#### 30. Compute the softmax score of sepallength.

In [74]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [75]:
sm = np.exp(sepallength)/sum(np.exp(sepallength))
sm[:5]

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836])

#### 31. Find the 5th and 95th percentile of iris's sepallength

In [76]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [77]:
np.percentile(sepallength,[5, 95])

array([4.6  , 7.255])

#### 32. Insert np.nan values at 20 random positions in iris_2d dataset

In [78]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [79]:
i, j = np.where(iris_2d)

In [80]:
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

In [81]:
print(iris_2d[:5])
print(iris_2d[25:30])

[[b'5.1' b'3.5' nan b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
[[b'5.0' b'3.0' b'1.6' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.6' b'0.4' b'Iris-setosa']
 [b'5.2' b'3.5' nan b'0.2' b'Iris-setosa']
 [b'5.2' b'3.4' b'1.4' b'0.2' nan]
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']]


#### 33. Find the number and position of missing values in iris_2d's sepallength (1st column)

In [82]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [83]:
iris_2d[:5]

array([[5.1, 3.5, nan, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [84]:
np.where(np.isnan(iris_2d[:,0]))

(array([ 17,  43,  91, 131], dtype=int64),)

In [85]:
np.isnan(iris_2d[:,0]).sum()

4

#### 34. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [86]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [87]:
iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

#### 35. Select the rows of iris_2d that does not have any nan value.

In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [89]:
nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])

In [90]:
iris_2d[nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

#### 36. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [91]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [92]:
np.corrcoef(iris_2d[:,0], iris_2d[:,2])

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

#### 37.Find out if iris_2d has any missing values.

In [93]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [94]:
np.any(np.isnan(iris_2d))

False

#### 38. Replace all ccurrences of nan with 0 in numpy array

In [95]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [96]:
iris_2d[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [97]:
iris_2d[np.isnan(iris_2d)] = 0

In [98]:
iris_2d[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

#### 39. Find the unique values and the count of unique values in iris's species

In [99]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [100]:
species_unique = np.unique(np.array([row.tolist()[4] for row in iris]))
species_unique

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype='|S15')

In [101]:
np.count_nonzero(species_unique)

3

In [102]:
np.unique(species, return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'),
 array([50, 50, 50], dtype=int64))

#### 40. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

- Less than 3 --> 'small'
- 3-5 --> 'medium'
- '>=5 --> 'large'

In [103]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [104]:
bins = np.array([3,5])

In [105]:
petallength_bin = np.digitize(iris[:, 2].astype('float'), [3, 5])

In [106]:
petallength_bin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [107]:
iris[:, 2]

array([b'1.4', b'1.4', b'1.3', b'1.5', b'1.4', b'1.7', b'1.4', b'1.5',
       b'1.4', b'1.5', b'1.5', b'1.6', b'1.4', b'1.1', b'1.2', b'1.5',
       b'1.3', b'1.4', b'1.7', b'1.5', b'1.7', b'1.5', b'1.0', b'1.7',
       b'1.9', b'1.6', b'1.6', b'1.5', b'1.4', b'1.6', b'1.6', b'1.5',
       b'1.5', b'1.4', b'1.5', b'1.2', b'1.3', b'1.5', b'1.3', b'1.5',
       b'1.3', b'1.3', b'1.3', b'1.6', b'1.9', b'1.4', b'1.6', b'1.4',
       b'1.5', b'1.4', b'4.7', b'4.5', b'4.9', b'4.0', b'4.6', b'4.5',
       b'4.7', b'3.3', b'4.6', b'3.9', b'3.5', b'4.2', b'4.0', b'4.7',
       b'3.6', b'4.4', b'4.5', b'4.1', b'4.5', b'3.9', b'4.8', b'4.0',
       b'4.9', b'4.7', b'4.3', b'4.4', b'4.8', b'5.0', b'4.5', b'3.5',
       b'3.8', b'3.7', b'3.9', b'5.1', b'4.5', b'4.5', b'4.7', b'4.4',
       b'4.1', b'4.0', b'4.4', b'4.6', b'4.0', b'3.3', b'4.2', b'4.2',
       b'4.2', b'4.3', b'3.0', b'4.1', b'6.0', b'5.1', b'5.9', b'5.6',
       b'5.8', b'6.6', b'4.5', b'6.3', b'5.8', b'6.1', b'5.1', b'5.3',
      

In [108]:
petallength_bin[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [109]:
iris[:,2][np.where(petallength_bin == 0)] = 'small'
iris[:,2][np.where(petallength_bin == 1)] = 'medium'
iris[:,2][np.where(petallength_bin == 2)] = 'large'

In [110]:
iris[:,2]

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium

In [111]:
iris[:5]

array([[b'5.1', b'3.5', 'small', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', 'small', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', 'small', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', 'small', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', 'small', b'0.2', b'Iris-setosa']], dtype=object)

#### 41. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [112]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [113]:
petallenght = iris_2d[:,2].astype('float')
petallenght[:3]

array([1.4, 1.4, 1.3])

In [114]:
sepallength = iris_2d[:,0].astype('float')
sepallength[:3]

array([5.1, 4.9, 4.7])

In [115]:
volume = (np.pi *petallenght * sepallength**2)/3
volume = volume[:, np.newaxis]

In [116]:
iris_2d = np.hstack([iris_2d, volume])
iris_2d[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092]], dtype=object)

#### 42. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

In [117]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [118]:
species = iris[:,4]
species[:3]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'], dtype=object)

In [119]:
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36], dtype=int64))


In [120]:
species_out[:10]

array([b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-setosa', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-virginica', b'Iris-setosa',
       b'Iris-versicolor'], dtype=object)

In [121]:
species_type = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

In [122]:
species_sample = np.random.choice(species_type, 50, p=[0.5, 0.25, 0.25])
species_sample

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa'], dtype='<U15')

#### 43. What is the value of second longest petallength of species setosa

In [123]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [124]:
petallength = iris[:,2]

In [125]:
sorted_unique = np.unique(np.sort(petallenght))[::-1]
sorted_unique

array([6.9, 6.7, 6.6, 6.4, 6.3, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4,
       5.3, 5.2, 5.1, 5. , 4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1,
       4. , 3.9, 3.8, 3.7, 3.6, 3.5, 3.3, 3. , 1.9, 1.7, 1.6, 1.5, 1.4,
       1.3, 1.2, 1.1, 1. ])

In [126]:
second_largest = sorted_unique[1]
second_largest

6.7

#### 44. Sort the iris dataset based on sepallength column.

In [127]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [128]:
iris[iris[:,0].argsort()][:5]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa']], dtype=object)

#### 45. Find the most frequent value of petal length (3rd column) in iris dataset.

In [129]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [130]:
values, count = np.unique(iris[:, 2], return_counts=True)
values[np.argmax(count)]

b'1.5'

#### 46. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

In [131]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [132]:
petalwidth = iris[:,3]

In [133]:
np.argwhere(petalwidth.astype(float) > 1.0)[0]

array([50], dtype=int64)

#### 47. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [134]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [135]:
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [136]:
a[(a < 10)] = 10
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048, 10.        ,
       10.        , 33.86670515, 41.466785  , 10.        , 29.17957314,
       44.67477576, 11.25090398, 10.08108276, 10.        , 11.76517714,
       48.95256545, 40.77247431, 10.        , 40.99501269, 14.42961361])

In [137]:
a[(a > 30)] = 30
a

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [138]:
np.where(a < 10, 10, np.where (a > 30, 30, a))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

#### 48. Get the positions of top 5 maximum values in a given array a.

In [139]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [140]:
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [141]:
a.argsort()[::-1][:5]

array([15, 10,  3,  7, 18], dtype=int64)

In [142]:
a[a.argsort()]

array([ 1.23122395,  6.31046763,  6.95688692,  7.69862289,  9.42510962,
       10.08108276, 11.25090398, 11.76517714, 14.42961361, 14.64009987,
       21.80136195, 27.62684215, 29.17957314, 33.86670515, 40.77247431,
       40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [143]:
np.sort(a)[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

#### 49. Compute the counts of unique values row-wise.

In [144]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [145]:
unique = {}
row_nr = 0
for row in arr:
    row_nr += 1 
    values, count = np.unique(row, return_counts=True)
    print('\nrow nr: ', row_nr)
    print(values)
    print(count)


row nr:  1
[1 3 4 5 6 8 9]
[1 2 1 1 1 2 2]

row nr:  2
[ 1  2  3  5  7  9 10]
[2 1 3 1 1 1 1]

row nr:  3
[2 4 5 6 8]
[3 2 3 1 1]

row nr:  4
[ 1  3  4  6  8  9 10]
[1 2 1 1 2 1 2]

row nr:  5
[1 2 3 6 7 8 9]
[2 2 2 1 1 1 1]

row nr:  6
[ 1  2  3  4  5  6  9 10]
[1 1 1 1 1 2 2 1]


In [146]:
def counts_of_all_values_rowwise(arr2d):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

In [147]:
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [148]:
arr = np.array([np.array(list('pięćdziesięciogroszówka')), np.array(list('konstantynopolitańczycy'))])
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

['a' 'c' 'd' 'e' 'g' 'i' 'k' 'l' 'n' 'o' 'p' 'r' 's' 't' 'w' 'y' 'z' 'ó'
 'ć' 'ę' 'ń']


[[1, 1, 1, 1, 1, 4, 1, 0, 0, 2, 1, 1, 2, 0, 1, 0, 2, 1, 1, 2, 0],
 [2, 2, 0, 0, 0, 1, 1, 1, 3, 3, 1, 0, 1, 3, 0, 3, 1, 0, 0, 0, 1]]

In [149]:
len('pięćdziesięciogroszówka')

23

In [150]:
len('konstantynopolitańczycy')

23

#### 50. Convert array_of_arrays into a flat linear 1d array.

In [151]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [152]:
np.hstack(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
np.array([a for arr in array_of_arrays for a in arr])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 51. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [154]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [155]:
dummy = np.zeros((arr.size, arr.max()+1))
dummy[np.arange(arr.size),arr] = 1
dummy[:, 1:]

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [156]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

In [157]:
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [158]:
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

#### 52. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

In [159]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [160]:
[i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small == val])]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]

#### 53. Create group ids based on a given categorical variable. Use the following sample from iris species as input.

In [161]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [162]:
group = []
uniqus = np.unique(species_small)

In [163]:
for i in uniqus:
    for j in species_small[species_small==i]:
        group_id = np.argwhere(uniqus == j).tolist()[0][0]
        group.append(group_id)

In [164]:
group

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]

#### 54.Create the ranks for the given numeric array a.

In [165]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [166]:
print('Arr rank: ',a.argsort().argsort())
print('Array: ', a)

Arr rank:  [4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


#### 55. Create a rank array of the same shape as a given numeric array a.

In [167]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [168]:
(a.ravel().argsort().argsort().reshape(a.shape))


array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

In [169]:
a.ravel()

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [170]:
a.ravel().argsort()

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6], dtype=int64)

In [171]:
a.ravel().argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1], dtype=int64)

In [172]:
a.ravel().argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

#### 56. Compute the maximum for each row in the given array.

In [173]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [174]:
a.max()

9

In [175]:
for row in a:
    print(row.max())

9
8
6
3
9


In [176]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [177]:
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 6, 3, 9])

#### 57. Compute the min-by-max for each row for given 2d numpy array.

In [178]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [179]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [180]:
np.amin(a, axis=1)

array([4, 1, 3, 3, 1])

In [181]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

#### 58. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

In [182]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

Array:  [0 0 3 0 2 4 2 2 2 2]


In [183]:
out = np.full(a.shape[0], True)
out

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [184]:
uniq = np.unique(a, return_index=True)[1]
uniq

array([0, 4, 2, 5], dtype=int64)

In [185]:
out[uniq] = False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

#### 59. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

In [186]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [187]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [188]:
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [189]:
categories = []
for group_val in np.unique(grouping_column):
    categories.append([group_val, numeric_column[grouping_column==group_val].mean()])
categories    

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

#### 60.Import the image from the following URL and convert it to a numpy array.

In [190]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [191]:
from io import BytesIO
from PIL import Image
import PIL, requests

In [192]:
response = requests.get(URL)
i = Image.open(BytesIO(response.content))

In [193]:
i = i.resize([150,150])

In [194]:
arr = np.asarray(i)

In [195]:
arr[0][:2]

array([[  9,  72, 125],
       [ 10,  73, 126]], dtype=uint8)

In [196]:
# Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

#### 61. Drop all nan values from a 1D numpy array

In [197]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [198]:
arr[~np.isnan(arr)]

array([1., 2., 3., 5., 6., 7.])

#### 62. Compute the euclidean distance between two arrays a and b.

In [199]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [200]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

#### 63.Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [201]:
arr = np.array([1, 3, 7, 1, 2, 6, 0, 1])
arr

array([1, 3, 7, 1, 2, 6, 0, 1])

In [202]:
some_list = np.array([1, 3, 7, 1, 2, 6, 0, 1])
peaks = []
for counter, value in enumerate(some_list[1:-1]):
    if (some_list[counter] > some_list[counter-1]) and (some_list[counter] > some_list[counter+1]):
        peaks.append(counter)
peaks

[2, 5]

In [203]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

#### 64. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

In [204]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [205]:
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


#### 65. Find the index of 5th repetition of number 1 in x.

In [206]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [207]:
u, c = np.unique(x, return_counts=True)
u, c

(array([1, 2, 3, 4]), array([7, 3, 2, 1], dtype=int64))

In [208]:
u[c>5]

array([1])

In [209]:
np.where(x == 1)[0][4]

8

In [210]:
[i for i, v in enumerate(x) if v == 1][4]

8

#### 66. Convert numpy's datetime64 object to datetime's datetime object

In [211]:
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64

numpy.datetime64('2018-02-25T22:10:10')

In [212]:
from datetime import datetime

In [213]:
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

#### 67. Compute the moving average of window size 3, for the given 1D array.

In [214]:
np.random.seed(100)
Z = np.random.randint(10, size=10)
Z

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [215]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [216]:
moving_average(Z)

array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])

In [217]:
np.convolve(Z, np.ones(3)/3, mode='valid') 

array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])

#### 68. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [218]:
def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

In [219]:
seq(5,10,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

#### 69. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

In [220]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [221]:
np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22'], dtype='datetime64[D]')

#### 70. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

In [222]:
arr = np.arange(15) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [223]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

In [224]:
gen_strides(arr)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])